// <auto-generated />
namespace JornalAberto2019.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class catNot : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(catNot));
        
        string IMigrationMetadata.Id
        {
            get { return "201807041606039_catNot"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
